### ISSUE TITLE
Consider reviewing new SeleniumHQ/docker-selenium repo

### ISSUE THREAD

**Issue by mtscout6** [vvo/docker-selenium-firefox-chrome-beta#5]
I have been working with the Selenium team to get an official Selenium docker image out there. While it may not be the perfect solution yet, the goal is to get it there as a community. The team would enjoy getting your feedback and potential support as we endeavor to acquire the Docker Official Repo status.

https://github.com/SeleniumHQ/docker-selenium
https://registry.hub.docker.com/repos/selenium/

**Comment by vvo** [comment]
finally it seems that there's a fully working image from selenium hq: https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneDebugChrome
