### ISSUE TITLE
Custom XVFB screen resolution

### ISSUE THREAD

**Issue by aaa2000** [vvo/docker-selenium-firefox-chrome-beta#8]
Is it possible to use an environment variable to set a custom XVFB screen resolution in the start.sh script ?

**Comment by vvo** [comment]
currently not feasible but you can submit a PR to do so, would be awesome @aaa2000 :)

**Comment by vvo** [comment]
it's only some bash scripting with defaults to the current values

**Comment by aaa2000** [comment]
I have seen that but I preferred to use https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneDebugChrome.

**Comment by vvo** [comment]
Yes seems like they did great work
